config/routes.rb
Rails.application.routes.draw do
  root 'photos#index'

  get 'user/:id' => 'users#index', as: 'user'
  post 'remark/:id' => 'remarks#create', as: 'create_remark'

  resources :photos

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true,
            length: { maximum: 250 }

  validates :image, presence:true

  has_attached_file :image,
                    styles: { medium: '300x300>', thumb: '100x100>'},
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image,
                                    content_type: ['image/jpeg', 'image/png']
end

app/models/remark.rb
class Remark < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo

  validates :text,
            presence: true,
            length: {maximum: 250}

  validates :rating,
            presence: true,
            numericality: {
                :only_integer => true,
                :allow_nil => true,
                greater_than_or_equal_to: 1,
                less_than_or_equal_to: 5
            }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, presence: true,
            length: { maximum: 250 }
  validates :email, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def access_denied(exeption)
    flash[:danger] = exeption.message
    redirect_to root_url
  end

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name) }
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, only: :create

  def index
    # @photos = Photo.all.order(created_at)
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
    @remark = Remark.new
    @remarks = Remark.where("photo_id = ?", @photo.id)
    if @remarks.empty?
      @average_remarks = 0
    else
      total = 0
      @remarks.each do |remark|
        total += remark.rating
      end
      @average_remarks = total/@remarks.size
    end
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    if @photo.save
      redirect_to root_url
    else
      render 'new'
    end
  end


  private

  def photo_params
    params.require(:photo).permit(:title, :image)
  end



end

app/controllers/remarks_controller.rb
class RemarksController < ApplicationController
  def create
    photo_id = params[:id]
    remark = Remark.new(remark_params)
    remark.photo_id = photo_id
    remark.user_id = current_user.id
    p remark
    if remark.save
      redirect_to photo_path(photo_id)
    else
      redirect_to photo_path(photo_id)
    end
  end
  private

  def remark_params
    params.require(:remark).permit(:text, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @photos = Photo.where("user_id = ?", @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/remarks_helper.rb
module RemarksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <b><%= link_to 'Photo Gallery', root_path, class: 'navbar-brand' %></b>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Hello, <%= current_user.name %>!
          </p>

          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', user_path(current_user), class: 'navbar-link' %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>

        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Log in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GallaryIgor</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
    <div class="container">
        <%= yield %>
    </div>
</body>
</html>

app/views/photos/index.html.erb
<% @photos.each do |photo| %>

    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%=image_tag photo.image %>
        <div class="caption">
          <p><%= link_to photo.title, photo_path(photo) %></p>
          <p>by: <%= photo.user.name %></p>
        </div>
      </div>
    </div>

<% end %>

app/views/photos/new.html.erb
<h1>Create new photo</h1>
<%= form_for  @photo,:html => {class:'form-horizontal col-md-9'}  do |f| %>

    <div class="form-group">
      <%= f.label :title, class: 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :title, class: 'form-control'  %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :image, class: 'col-md-3 control-label'	  %>
      <div class="col-md-9">
        <%= f.file_field :image, id: 'exampleInputFile'%>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit class: 'col-md-offset-3 btn btn-lg btn-primary' %>
    </div>

<% end %>

app/views/photos/show.html.erb
<h1><%= @photo.title %></h1>
<div>
  <%= image_tag @photo.image.url(:medium) %>
  <p>
    Avarage score: <%= @average_remarks %>
  </p>
</div>
<hr />

<% if user_signed_in? %>
    <%= form_for @remark, url: create_remark_path(@photo.id) do |f| %>
        <div class="form-field">
          <%= f.submit 'Add comment', class:'btn btn-primary' %>
        </div>
        <div class="form-field">
          <%= f.label :text %>
          <%= f.text_field :text, autofocus: true, class:'form-control' %>
        </div>
        <div class="form-field">
          <%= f.label 'Score:', :rating %>
          <%= f.select(:rating, options_for_select([[1, 1], [2, 2],[3,3], [4,4], [5,5]], :selected => params[:ratings]), class: 'form-control') %>
        </div>
    <% end %>
    <hr />
<% end %>
<%	if @remarks %>
    <% @remarks.each do |remark| %>
        <i>by: <%= remark.user.name %>, score: <%= remark.rating %> </i>
        <div>
          <%= remark.text %>
        </div>
        <hr/>
    <% end %>
<% end %>

app/views/users/index.html.erb
<% %>
<h1>
  <%= @user.name %>'s profile
  <%= link_to 'Edit', edit_user_registration_path(current_user), class: "btn btn-default" %>
</h1>


<div>
  My photos: <%= link_to 'Create new photo', new_photo_path(current_user), class: "btn btn-default" %>
</div>

<table class="table">
  <tr>
    <th>Photo</th>
    <th>Title</th>
    <th>Action</th>
  </tr>

    <% @photos.each do |photo| %>
      <tr>
        <td><%=image_tag photo.image.url(:thumb)%></td>
        <td><%= link_to photo.title, photo_path(photo) %></td>
        <td>
          <%=link_to 'Remove', photo_path(photo), method: :delete %>
        </td>
      </tr>
    <% end%>

</table>